# Generated by Django 3.0.5 on 2020-04-13 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
            ],
            managers=[
                ('tours', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_city', models.CharField(max_length=100)),
                ('show_state', models.CharField(max_length=3)),
                ('show_time', models.DateTimeField()),
                ('show_date', models.DateTimeField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour_Manager.Tour')),
            ],
            managers=[
                ('shows', django.db.models.manager.Manager()),
            ],
        ),
    ]
