# Generated by Django 3.0.5 on 2020-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Manager', '0002_auto_20200414_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(max_length=25),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(max_length=25),
        ),
    ]
