# Generated by Django 3.0.7 on 2020-06-08 05:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_image', models.FileField(upload_to='media/')),
                ('art_name', models.CharField(max_length=100)),
                ('art_date', models.DateField(max_length=25)),
            ],
            managers=[
                ('arts', django.db.models.manager.Manager()),
            ],
        ),
    ]
