# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=45)),
                ('recovery_email', models.CharField(max_length=100)),
                ('password_last_updated', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('admins', django.db.models.manager.Manager()),
            ],
        ),
    ]
