# Generated by Django 3.0.5 on 2020-05-25 22:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=1000)),
                ('post_date', models.DateField(auto_now=True)),
                ('post_media', models.FileField(upload_to='media/')),
            ],
            managers=[
                ('newsfeed_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
