# Generated by Django 3.0.5 on 2020-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='post_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
