# Generated by Django 3.0.5 on 2020-06-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed_Manager', '0002_newsfeed_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='post_content',
        ),
    ]
