# Generated by Django 3.0.5 on 2020-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_price', models.FloatField()),
                ('item_description', models.CharField(max_length=500)),
            ],
        ),
    ]
