# Generated by Django 3.0.5 on 2020-05-10 08:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
                ('stores', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='store',
            name='item_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
