# Generated by Django 3.0.5 on 2020-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Manager', '0004_auto_20200510_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
