# Generated by Django 3.0.5 on 2020-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Manager', '0005_auto_20200510_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='item_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
