# Generated by Django 3.0.5 on 2020-05-31 09:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_text', models.CharField(max_length=2000)),
                ('about_me_image', models.ImageField(upload_to='media/')),
            ],
            managers=[
                ('about_me_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
