# Generated by Django 3.0.5 on 2020-04-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('album_date', models.DateField(max_length=25)),
                ('buy_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('song_date', models.DateField(blank=True)),
                ('song_lyrics', models.CharField(max_length=2000)),
                ('buy_link', models.CharField(max_length=250)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Manager.Album')),
            ],
        ),
    ]
