# Generated by Django 3.0.5 on 2020-04-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='buy_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='buy_link',
        ),
    ]
