# Generated by Django 3.0.5 on 2020-04-30 06:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Manager', '0002_auto_20200428_0306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('albums', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('songs', django.db.models.manager.Manager()),
            ],
        ),
    ]
