# Generated by Django 3.0.5 on 2020-05-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Manager', '0003_auto_20200430_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_lyrics',
        ),
    ]
